### PR TITLE
Added all 5 profiles

### PR DESCRIPTION
**Pull request by brendanwhitfield**
~~`SUMMARY.md` was *not* updated for ease of merging.~~ Once the chosen directory structure gets merged, I can modify this PR to match.

### CODE REVIEW

**Comment by qwertos** [comment]
Directory structure has been updated. Please `git mv` to new structure and I'll merge. :smile:

**Comment by brendanwhitfield** [comment]
ok, should be good to go

**Comment by msoucy** [comment]
LGTM :+1: :ship: it

**Comment by qwertos** [comment]
Thanks. Merged.

**Pull request merged**
