### PR TITLE
 Added raspberry pi profile

### PR DESCRIPTION
**Pull request by Berulacks**
Totally forgot about this one, sorry everyone!

### CODE REVIEW

**Comment by Berulacks** [comment]
Nevermind. I am an idiot.

**Comment by qwertos** [comment]
FYI  - RPI is still missing, waiting on #27. This will close that. Do you want me to merge?

**Comment by Berulacks** [comment]
Ah, didn't know Knepper's didn't fit the criteria!

Yeah, lets merge away, boss.

**Comment by qwertos** [comment]
Cool Merged :+1:

**Pull request merged**
