### PR TITLE
New template

### PR DESCRIPTION
**Pull request by brendanwhitfield**
I realize everyone's already using the current template, so this doesn't necessarily need to get used now, but it could be nice for future classes.

This is a new version using blockquotes to demarcate question vs. answer. That way, it doesn't feel like such a wall of text, and does away with the nested lists.

### CODE REVIEW

**Comment by msoucy** [comment]
Do you want this one, or #25, to be merged in?

**Comment by brendanwhitfield** [comment]
Apologies,
This one, if you deem the format acceptable.

**Comment by msoucy** [comment]
I love it, this one seems so much nicer - @qwertos I'm in favor of merging, should we push to get new pull requests to match this instead? Otherwise I might just do it myself after they're all merged.

**Comment by qwertos** [comment]
I'm of the opinion of, lets merge what comes in as it comes in, compare formatting, spin up issues as needed to solidify formatting.

**Comment by qwertos** [comment]
Please `git mv` and I'll merge. :smile:

**Comment by brendanwhitfield** [comment]
moved

**Comment by qwertos** [comment]
Wait I just realized this was for a blank template... Meh... It makes more sense to be this directory anyway... Just hope people can find it... Merged.

**Pull request merged**
