### PR TITLE
Add RIT Computer Science Community to FOSS Ecosystems

### PR DESCRIPTION
**Pull request by chrissprague**

### CODE REVIEW

**Comment by zg** [comment]
:+1:

**Comment by ryansb** [comment]
Why is everything in a block quote?

**Comment by chrissprague** [comment]
I believe that's how the other pages were designed, so I followed that. Our logo and link to the homepage aren't in the blockquote. I can remove the block quote if you think it would make more sense.

**Comment by ryansb** [comment]
Hm, so it is. Since you're following existing formatting, :100:

**Pull request closed without merging**
